version: 2.1

orbs:
  heroku: circleci/heroku@1.2 # For easier deployment to heroku

jobs:
  ## Re-build the image with the latest changes
  build:
    docker:
      - image: circleci/node:14.16.1
    steps:
      - checkout
      - run: echo "create compressed build"
      - run: cd client && npm run build

  ## Run all my tests to make sure everything works
  test: ## TODO - persist artifacts for each run
    docker:
      - image: circleci/node:14.16.1
    steps:
      - checkout
      - run: echo "Run test suite"
      - run: cd client && npm run test

workflows:
  build_test:
    jobs:
      - build

      - test:
          requires:
            - build

      - heroku/deploy-via-git:
          pre-steps:
            - run: cd ~/server
          filters:
            branches:
              only: master
          force: true
          maintenance-mode: true
          requires:
            - test

